name: Client Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
  steps:
  - name: Checkout library
    uses: actions/checkout@v3
  - name: Install with Maven
    run: mvn install
  - uses: actions/setup-python@v4
    with:
        python-version: '3.10'
  - name: Checkout private ODO repository
    uses: actions/checkout@v3
    with:
      repository: cmu-pasta/open_dependency_observatory
      token: ${{ secrets.GH_PAT }}
      path: odo

